travis:
  secure:
    BINSTAR_TOKEN: R/LN3j948BIk9pUQTyzVMlQkhIVM+M8Y2m43hBpXZhaPO18eNbyZNeyfgrpKjK+eXxc1u54rzYVZsNHpt4C+CvvhAwQ+OvaYX9186zsvl3uZGzGr+Ugns5V8ThP+SZ4WmFwkbI2EIPL4VdxFE3KHjLSi+VB/UZXLXzV2p+blhKuuwIXL5QFcS/eWngRyZ9+ui7y96bhr2AJ83QlG94HB77YrKq6CNgk5thbyj1Xh44FOGKhnWfdymuD1XfpdfQ02vg7P/u4qeG9c2eMySu0GZpad0g0jzD1h/47apcqu3Q3Wbjurn80ARWRAy0s/rWsmmWNIabcTv3b18KkDaq+/JQy9lFgayHB+d3YNBc+0a1tbrYG/hyLlFDeuBY4cnFn/La+SSIxtkvtg7esVjibP5ymsRciw+PHn1n126nHnHi4xg7DgEFyqYqy/pdRlJWEjE+hdVPLznGzH+aWTtC9tY7Za7iyi72FBCan2xLEhbjTj46NQfIkJvVRKFGCG7nLR/2/2wDf4wppoxtqtMzMfcpaEPWaSi46bTlp+yuG8DI2jHtAl0Qv01E1hHBggx+nYz58jS4hZRujSRpcjPZ//v7/CmPlHXzGHh3gvBtFn+mCIcC7eg7MYhcmddiZkerygvM6OumQet7lJMOU17UFmcE4aVsmvJdQReiLF4VnaFeI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
